### PR TITLE
NLO QCD+EWK predictions updated in Openloops

### PR DESCRIPTION
**Pull request by GurpreetSinghChahal**
The NLO QCD+EWK predictions are updated in the openloops package that are needed to generate the Monte Carlo samples with the new Sherpa 2.2.5. We need this feature in 10_3, 10_2 and 9_3

FYI @alberto-sanchez, @qliphy, @efeyazgan

### CODE REVIEW

**Comment by GurpreetSinghChahal** [comment]
FYI @alberto-sanchez, @qliphy, @efeyazgan

**Comment by alberto-sanchez** [comment]
a release to include in cmsdist will be needed and in top of that we need to download the OpenLoops Process Library. I can take care of it, just let me know. I see that the available list of process is larger than the one installed in 1.3.1

**Comment by alberto-sanchez** [comment]
@smuzaffar can we merge this and create the appropriate directory for the version we will include in the release, it should be something like v2.0.b.
I have download to https://github.com/alberto-sanchez/openloops/tree/cms/v2.0.b/process_src all the process library for this release.

**Comment by smuzaffar** [comment]
@alberto-sanchez , I have created https://github.com/cms-externals/openloops/commits/cms/v2.0.b branch based on your branch https://github.com/alberto-sanchez/openloops/commits/cms/v2.0.b.
If this looks good then I can go ahead with cmsdist PR.

**Comment by alberto-sanchez** [comment]
That looks good, however I just learn that scons 1.2.0 (in cmsdist) does not work with this. I am using the one included in this OpenLoops version, which is scons v3.0.1, how we can procced, with this?. Should we upgrade scons or make use of the one included?. If scons is just used for building the OpenLoops library, should be safe to use the included one. What do you think?.

**Comment by davidlange6** [comment]
we should have one version of scons... should be simple to upgrade it as part of this PR

**Comment by alberto-sanchez** [comment]
Thanks @davidlange6, it is clear to me now.

**Comment by smuzaffar** [comment]
cmsdist PR for 10.3.X is https://github.com/cms-sw/cmsdist/pull/4377

**Comment by smuzaffar** [comment]
@alberto-sanchez , this is also requested for 10.2.X and 9.3.X. I guess sherpa 2.2.5 ( https://github.com/cms-externals/sherpa/pull/12) is also needed for 10.2.X and 9.3.X?

**Comment by efeyazgan** [comment]
yes

**Comment by smuzaffar** [comment]
done
10.2.X: https://github.com/cms-sw/cmsdist/pull/4385
9.3.X: https://github.com/cms-sw/cmsdist/pull/4384

**Comment by alberto-sanchez** [comment]
We need this for 7.1.x as well, thanks

**Comment by smuzaffar** [comment]
for 7.1.X: https://github.com/cms-sw/cmsdist/pull/4414

**Pull request closed without merging**
